{% set name = "cuda-compat" %}
{% set driver_version = "595.45.04" %}
{% set cuda_version = "13.2.0" %}
{% set cuda_major_minor = cuda_version.split('.')[:2] | join('.') %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}-split
  version: {{ cuda_version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_compat/{{ platform }}/cuda_compat-{{ platform }}-{{ driver_version }}_cuda{{ cuda_major_minor }}-archive.{{ extension }}
  sha256: f1a9cfd13396d78ddef6dfe5fa6fdeb783a66fa1f4c36494ae2fa7fd9caa9fda  # [linux64]
  sha256: 03f561d067b60cb64cad3dfac4b9c5e284a14815d1158aa732eb156cc658abbd  # [aarch64]

build:
  number: 1
  skip: true  # [osx or win or ppc64le]
  script_env:
    - COMPAT_DRV_VERSION={{ driver_version }}
    - COMPAT_CUDA_VERSION={{ cuda_version }}
    # The cuda-compat UMD is not compatible with every KMD. We implement an install-time
    # check using __cuda run constraints below. However, we also do runtime checks in case
    # the system administrator updates the KMD after the conda environment is created.
    # https://docs.nvidia.com/deploy/cuda-compatibility/forward-compatibility.html#id1
    - SUPPORTED_KMD_VERSIONS=535,550,570,580,590

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:
  - name: cuda-compat
    files:
      - etc/conda/activate.d/cuda-compat_activate.sh
      - etc/conda/deactivate.d/cuda-compat_deactivate.sh
      - etc/cuda-compat/
    requirements:
      run:
        - {{ pin_subpackage("cuda-compat-impl", exact=True) }}
    test:
      commands:
        - exit 0
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
        Package containing all the necessary CUDA driver files related to forward
        compatibility. This compatibility enables newer CUDA runtimes to work with
        older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-compat-impl
    version: {{ driver_version }}
    files:
      - cuda-compat
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      run_constrained:
        # The cuda-compat UMD is not compatible with every KMD. These constraints are an
        # install-time check that the user has the correct KDM for compat to be supported.
        # However, we also do runtime checks in case the system administrator updates the
        # KMD after the conda environment is created.
        # https://docs.nvidia.com/deploy/cuda-compatibility/forward-compatibility.html#id1
        - __cuda 12.2|12.4|12.8|13.0|13.1
        # There is no point to updating across major CUDA versions if the device is not
        # supported by newer toolkit.
        - __cuda_arch >=7.5
    test:
      commands:
        - test -f $PREFIX/cuda-compat/libcuda.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcuda.so.1
        - test -L $PREFIX/cuda-compat/libcuda.so
        - test -f $PREFIX/cuda-compat/libnvidia-nvvm.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so.4
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so
        - test -f $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.1
        - test -f $PREFIX/cuda-compat/libcudadebugger.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcudadebugger.so.1
        - test -f $PREFIX/cuda-compat/libnvidia-gpucomp.so.{{ driver_version }}
        - test -f $PREFIX/cuda-compat/libnvidia-nvvm70.so.4
        - test -f $PREFIX/cuda-compat/libnvidia-tileiras.so.{{ driver_version }}
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
        Package containing all the necessary CUDA driver files related to forward
        compatibility. This compatibility enables newer CUDA runtimes to work with
        older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Compatibility Platform
  description: |
    Package containing all the necessary CUDA driver files related to forward
    compatibility. This compatibility enables newer CUDA runtimes to work with
    older display drivers. Used for Tesla cards only.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-compat
  recipe-maintainers:
    - conda-forge/cuda
